name: Build

on: [push]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install modules
        run: yarn install --frozen-lockfile
      - run: yarn build --env production
      - name: Build for Chrome
        run: sh ./tools/make-chrome.sh
      - name: Build for Firefox
        run: sh ./tools/make-firefox.sh
