name: Build

on: [push]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Enable Node.js Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install modules
        run: yarn install --frozen-lockfile

      - run: yarn build --env production

      - name: Build for Chrome
        run: sh ./tools/make-chrome.sh

      - name: Build for Firefox
        run: sh ./tools/make-firefox.sh

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-search-navigator
          path: |
            build/chrome/*.zip
            build/firefox/*.zip
          if-no-files-found: error
