name: Bump Version

on: [ push, workflow_dispatch ]

env:
  CURRENT_VERSION: ""
  NEXT_VERSION: ""

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Detect current version
        run: |
          CURRENT_VERSION=$(sh tools/version.sh)
          echo "$CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Detect next version
        id: bump-version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.CURRENT_VERSION }}
          version-fragment: feature

      - name: Replace version in manifest
        run: |
          NEXT_VERSION=${{ steps.bump-version.outputs.next-version }}
          awk '{ gsub("\"version\":.+", "\"version\": \"'"$NEXT_VERSION"'\",") }1' src/manifest.json > src/manifest.json.tmp
          mv -f src/manifest.json.tmp src/manifest.json
          cat src/manifest.json

      - name: Verify modified manifest
        run: jq empty < src/manifest.json

      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'src/manifest.json'
          default_author: github_actions
          message: Bump version to ${{ steps.bump-version.outputs.next-version }}
